theme: jekyll-theme-leap-day
title: Welcome to Caleb's Homepage!
description: This page will demonstrate some of the progress I have made as a software engineering student at SNHU.  Bookmark the page to stay up to date with any project changes!
